### ISSUE TITLE
NIST/NRC Corner data

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/exp#29]
Thanks for getting the data up so quickly after the test.  Can you add to the readme the cage distance from the wall and an image showing the TC layout in the cage.

**Comment by mcgratta** [comment]
Check out what I did and let me know if there's anything missing.

**Comment by drjfloyd** [comment]
I'm not sure if this would be better or more confusing:

As the burner moved beyond 20 cm, the thermocouple array was moved the same amount so that the burner was always below the array, or the cage distance from the wall was Max(0 cm, burner distance - 20 cm).

**Comment by mcgratta** [comment]
Try now

**Comment by drjfloyd** [comment]
I think that is clear.  Thanks.
